server :
  port : 8761

eureka:
    instance:
      #定义注册中心服务的ip
      hostname: 10.61.14.26
    clent:
        #不向注册中心注册自己
        registerWithEureka: false
        #注册中心的职责就是维护服务的实例,并不需要检索服务
        fetchRegistry: false
        #注册中心的访问地址
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/